# Generated by Django 2.2.17 on 2020-11-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk', '0008_sqlquery_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlquery',
            name='model',
            field=models.CharField(max_length=256, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sqlquery',
            name='database',
            field=models.CharField(max_length=256, db_index=True, null=True),
        ),
    ]
